/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import bdproiect.Beneficiar;
import bdproiect.ConnectionJDBC;
import bdproiect.ModelPieChart;
import bdproiect.PieChart;
import java.awt.Color;

import bdproiect.ValutaDispLoad;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Petru
 */
public class ValSchimbChart extends javax.swing.JFrame {

    /**
     * Creates new form ValSchimbChart
     */
    public ValSchimbChart() throws SQLException, ClassNotFoundException {
        
        initComponents();
        pieChart2.setChartType(PieChart.PeiChartType.DONUT_CHART);
        pieChart2.clearData();
        showData();
    }

   private void showData() throws SQLException, ClassNotFoundException{
       try (Connection conn = ConnectionJDBC.getConnection())
        {
            String sql = "select sum(suma),valutaschimb from beneficiar group by valutaschimb";
            PreparedStatement statement = conn.prepareStatement(sql);
            ResultSet result = statement.executeQuery();
            int index=0;
            while (result.next()) {
                int suma=result.getInt(1);
                String clasa = result.getString(2);
                
               pieChart2.addData(new ModelPieChart(clasa, suma, getColor(index++)));
                
            }
        }
        catch (SQLException ex)
        {
            ex.printStackTrace();
        }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modelPieChart1 = new bdproiect.ModelPieChart();
        pieChart2 = new bdproiect.PieChart();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));

        pieChart2.setChartType(bdproiect.PieChart.PeiChartType.DONUT_CHART);
        pieChart2.setMinimumSize(new java.awt.Dimension(200, 200));
        pieChart2.setName(""); // NOI18N

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        jTextField1.setText("Grafic Valute Schimbate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pieChart2, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pieChart2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValSchimbChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValSchimbChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValSchimbChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValSchimbChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ValSchimbChart().setVisible(true);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(ValSchimbChart.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ValSchimbChart.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

 
    
    
    private Color getColor(int index){
    Color [] color = new Color [] {new Color(255,102,102),new Color(58,55,227),new Color(206,215,33),new Color(29,217,214),new Color(43,34,250),new Color(200,169,86),new Color(255,102,0)};
    return color[index];
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private bdproiect.ModelPieChart modelPieChart1;
    private bdproiect.PieChart pieChart2;
    // End of variables declaration//GEN-END:variables
}
